map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

proxy_temp_path /var/cache/nginx/proxy_temp;
proxy_cache_path /var/cache/nginx/proxy_cache levels=1:2 keys_zone=cache_zone:10m inactive=60m;

proxy_temp_file_write_size 128k;

server {
    listen 80;
    server_name aiworkshop.su www.aiworkshop.su;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_buffering on;
    proxy_buffer_size 16k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 32k;
    proxy_max_temp_file_size 1024m;
    
    proxy_connect_timeout 30s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    
    location = /favicon.ico {
        access_log off;
        log_not_found off;
        return 204;
    }

    location / {
        proxy_pass http://frontend:3000;
        
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
    }

    location /api {
        proxy_pass http://backend:8000;
        
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    location /monitoring {
        proxy_pass http://grafana:3001;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /board/ {
        proxy_pass http://focalboard:4000/;
        proxy_set_header X-Forwarded-Prefix /board;
        
        proxy_buffering off;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
    }

    location /board/static/ {
        proxy_pass http://focalboard:4000/static/;
        proxy_set_header X-Forwarded-Prefix /board;
        
        proxy_buffer_size 32k;
        proxy_buffers 16 32k;
        proxy_busy_buffers_size 128k;
        
        proxy_cache cache_zone;
        proxy_cache_valid 200 302 1h;
        proxy_cache_valid 404 1m;
        proxy_cache_key "$scheme$request_method$host$request_uri";
        add_header X-Cache-Status $upstream_cache_status;
        
        gzip on;
        gzip_types text/css text/javascript application/javascript;
        gzip_comp_level 6;
        gzip_min_length 1000;
    }
}